export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const LOGOUT = 'LOGOUT';

export const SHOW_ALERTS = 'SHOW_ALERTS';  
export const REMOVE_ALERTS = 'REMOVE_ALERTS';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const NEW_LINK_SUCCESS = 'NEW_LINK_SUCCESS';
export const NEW_LINK_ERROR = 'NEW_LINK_ERROR';

export const RESET_STATE = 'RESET_STATE';

export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_FOLDER = 'SET_FOLDER';
export const SET_DOWNLOADS = 'SET_DOWNLOADS';